language: ruby
bundler_args: --without development
script: bundle exec rspec spec
env: TIMEOUT=10
rvm:
  - ruby-2.1.2
gemfile:
  - gemfiles/active_record32.gemfile
  - gemfiles/active_record40.gemfile
  - gemfiles/active_record40_mysql.gemfile
services:
  - mongodb
  - rabbitmq
  - redis-server
